# Generated by Django 3.0 on 2019-12-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='core.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_at', models.DateField()),
                ('value', models.DecimalField(decimal_places=10, max_digits=14)),
                ('type', models.CharField(max_length=10)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='core.Ticker')),
            ],
        ),
    ]
