# Generated by Django 3.0 on 2020-02-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='ticker',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
